name: handrail_chat
description: Flutter and Dart SDK for embedding Handrail Chat in applications.
version: 0.1.21

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  unorm_dart: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.0
